import { useMemo } from "react";
import { useForm, useWatch } from "react-hook-form";

const defaultValues = {
  Availability: "",
  AvailabilityDetail: "",
  CHOCounting: "",
  ChristianName: "",
  ComputerType: "",
  ContactDate: "",
  CurrentCGMWear: "",
  CurrentStudy: "",
  DKAExpreience: "",
  DateDetailsUpdated: "",
  DateOfBirth: "",
  DateOfDiagnosisOfT1D: "",
  DiabetesEducator: "",
  DiabetesManagementPump: "",
  DiabeticHistory: "",
  Discussionheld: "",
  DoNotCallUntil: "",
  EmailAddress: "",
  Endocrinologist: "",
  ExerciseDetail: "",
  ExerciseType: "",
  FrequencyOfSBGM: "",
  Gender: "",
  HadAbnormalkidney: false,
  HadFeetNeuropathy: false,
  HadRetionopathyDiagnosis: false,
  HadSevereHypoglycaemiaEvents: false,
  HadUnawareHypo: false,
  HasInternetAccess: false,
  Insulin: "",
  LatestHbA1cReading: "",
  LatestHbA1cReadingDate: "",
  Logistics: "",
  NextStep: "",
  OtherMedicalIssue: "",
  PWODReferral: "",
  PastCGMWear: "",
  PatientBio: "",
  PhoneNumber: "",
  PreferedContactMethod: "",
  PreferedContactTime: "",
  PreviousStudy1: "",
  PreviousStudy2: "",
  PreviousStudy3: "",
  State: "",
  StudyForConsideration: "",
  Subrub: "",
  Surname: "",
  WillComeToStVincent: false,
};

export const useAddPatient = () => {
  const {
    handleSubmit,
    register,
    control,
    formState,
    errors,
    setValue,
  } = useForm({
    defaultValues,
  });

  return {
    register,
    control,
    errors,
    setValue,
    dirty: useMemo(() => formState.isDirty, [formState.isDirty]),
    state: useWatch({ control, defaultValue: defaultValues }),
    onSubmit: handleSubmit((state) => console.log(state)),
    years: useMemo(
      () => [
        "2021",
        "2020",
        "2019",
        "2018",
        "2017",
        "2016",
        "2015",
        "2016",
        "2015",
        "2014",
        "2013",
        "2012",
        "2011",
        "2010",
        "2009",
        "2008",
        "2007",
        "2006",
        "2005",
        "2004",
        "2003",
        "2002",
        "2001",
        "2000",
        "1999",
        "1998",
        "1997",
        "1996",
        "1995",
        "1994",
        "1993",
        "1992",
        "1991",
        "1990",
      ],
      []
    ),
  };
};
